conditions:
  kiwi:
    tree: true
    # bird: true
  # etc

mongodb:
  auth:
    enabled: true
  metrics:
    enabled: true

queue:
  backend:
    nats: true
    # kafka: false
    # sqs: false
    # etc
#  nats:
#    auth:
#      user: "awakari"
#      password: "awakari"
#    uri: "nats://nats:4222"
#    pollTimeoutMillis: 10
#  log:
#    level: -4

conditions-kiwi-tree-complete:
  db:
#    hostname: mongodb
    name: conditions-kiwi-tree-partial
#    table:
#      # Database table name to use.
#      name: "kiwi-tree"
#      lockTime:
#        # Tree node lock timeout for the update operations.
#        children: "1000s"
#        # Tree node keys lock timeout for the insert operations.
#        insert: "1000s"
    username: root
    password:
#      raw: "password"
      secret:
        enabled: true
#        name: "mongodb"
#        key: "mongodb-root-password"
#  log:
#    level: -4

conditions-kiwi-tree-partial:
  db:
#    hostname: mongodb
    name: conditions-kiwi-tree-partial
#    table:
#      # Database table name to use.
#      name: "kiwi-tree"
#      lockTime:
#        # Tree node lock timeout for the update operations.
#        children: "1000s"
#        # Tree node keys lock timeout for the insert operations.
#        insert: "1000s"
    username: root
    password:
#      raw: "password"
      secret:
        enabled: true
#        name: "mongodb"
#        key: "mongodb-root-password"
#  log:
#    level: -4

subscriptions:
  api:
    uri:
      kiwi:
        tree:
          complete: "conditions-kiwi-tree-complete:8080"
          partial: "conditions-kiwi-tree-partial:8080"
  db:
#    hostname: mongodb
#    name: "subscriptions"
#    table:
#      # Database table name to use.
#      name: "subscriptions"
    username: root
    password:
#      raw: "password"
      secret:
        enabled: true
#  log:
#    level: -4

matches:
  db:
#    hostname: mongodb
#    name: "matches"
#    table:
#      # Database table name to use.
#      name: "matches"
    username: root
    password:
#      raw: "password"
      secret:
        enabled: true
#  log:
#    level: -4

#router:
#  api:
#    matches:
#      batchSize: 100
#      uri: "matches:8080"
#    consumer:
#      backoff: "1s"
#      uri: "consumer:8080"
#  log:
#    level: -4
#  queue:
#    batchSize: 100
#    fallback:
#      enabled: true
#      suffix: "fallback"
#    limit: 1000
#    backoff:
#      empty: "1s"
#      error: "1s"
#    uri: "queue:8080"

resolver:
  api:
    conditions:
      kiwi:
#        batchSize: 100
        tree:
          completeUri: "conditions-kiwi-tree-complete:8080"
          partialUri: "conditions-kiwi-tree-partial:8080"
#    subscriptions:
#      batchSize: 100
#      uri: "subscriptions:8080"
#    matches:
#      uri: "matches:8080"
#    router:
#      backoff: "1s"
#      uri: "router:8080"
#  log:
#    level: -4
#  queue:
#    batchSize: 100
#    fallback:
#      enabled: true
#      suffix: "fallback"
#    limit: 1000
#    backoff:
#      empty: "1s"
#      error: "1s"
#    uri: "queue:8080"
