apiVersion: v2
name: core
description: Helm chart for the Awakari Core system deployment

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "latest"

dependencies:

  - name: mongodb-sharded
    version: 6.3.2
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.internal
    alias: mongodb

  - name: nats
    version: 7.5.13
    repository: https://charts.bitnami.com/bitnami
    condition: queue.backend.nats
    alias: nats

  - name: redis-cluster
    version: 8.6.9
    repository: https://charts.bitnami.com/bitnami
    alias: redis

  - name: jaeger
    version: 0.71.10
    repository: https://jaegertracing.github.io/helm-charts
    condition: tracing.enabled

  - name: semaphore-nats
    version: 0.0.0
    repository: "file://../../../semaphore-nats/helm/semaphore-nats"
    condition: semaphore.backend.nats
    alias: semaphore

  - name: queue-nats
    version: 0.0.0
    repository: "file://../../../queue-nats/helm/queue-nats"
    condition: queue.backend.nats
    alias: queue

  - name: conditions-number
    alias: conditionsnumber
    version: 0.0.0
    repository: "file://../../../conditions-number/helm/conditions-number"

  - name: conditions-text
    alias: conditionstext
    version: 0.0.0
    repository: "file://../../../conditions-text/helm/conditions-text"

  - name: messages
    version: 0.0.0
    repository: "file://../../../messages/helm/messages"

  - name: matches
    version: 0.0.0
    repository: "file://../../../matches/helm/matches"

  - name: subscriptions-proxy
    alias: subscriptionsproxy
    version: 0.0.0
    repository: "file://../../../subscriptions-proxy/helm/subscriptions-proxy"

  - name: reader
    version: 0.0.0
    repository: "file://../../../reader/helm/reader"

  - name: evaluator
    version: 0.0.0
    repository: "file://../../../evaluator/helm/evaluator"

  - name: writer
    version: 0.0.0
    repository: "file://../../../writer/helm/writer"

  - name: resolver
    version: 0.0.0
    repository: "file://../../../resolver/helm/resolver"
