# to be used for the alternative chart:
# https://nats-io.github.io/k8s/helm/charts/

container:
  image:
    tag: 2.11.6-scratch

config:
  auth:
    enabled: true
    user: "awakari"
    password: "awakari"
  cluster:
    enabled: false
    replicas: 1
  jetstream:
    enabled: true
    fileStore:
      pvc:
        size: 10Gi
        storageClassName: "default"

# podTemplate:
#  topologySpreadConstraints:
#    kubernetes.io/hostname:
#      maxSkew: 1
#      whenUnsatisfiable: DoNotSchedule

natsBox:
  enabled: false
