name: Publish

on:
  push:
    branches:
      - "master"

env:
  COMPONENT: core
  VERSION: latest
  CHART_VERSION: 0.0.0

jobs:

  helm:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.0

      - name: Build Helm Chart
        run: |
          mkdir package
          helm package . --version ${CHART_VERSION} --destination package
          cd package
          helm repo index .

      - name: Publish Helm Chart
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: package
