name: Staging

on:
  push:
    branches:
      - "master"

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.6

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Registry login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_ACCESS_TOKEN }}

      - name: Staging
        run: make staging

  helm:
    runs-on: ubuntu-latest
    steps:

      - name: clone core
        uses: actions/checkout@v3
        with:
          path: "core"

      - name: clone conditions-number
        uses: actions/checkout@v3
        with:
          path: "conditions-number"
          repository: awakari/conditions-number
          token: ${{ secrets.CLONE_PAT }}

      - name: clone conditions-text
        uses: actions/checkout@v3
        with:
          path: "conditions-text"
          repository: awakari/conditions-text
          token: ${{ secrets.CLONE_PAT }}

      - name: clone evaluator
        uses: actions/checkout@v3
        with:
          path: "evaluator"
          repository: awakari/evaluator
          token: ${{ secrets.CLONE_PAT }}

      - name: clone matches
        uses: actions/checkout@v3
        with:
          path: "matches"
          repository: awakari/matches
          token: ${{ secrets.CLONE_PAT }}

      - name: clone messages
        uses: actions/checkout@v3
        with:
          path: "messages"
          repository: awakari/messages
          token: ${{ secrets.CLONE_PAT }}

      - name: clone queue-nats
        uses: actions/checkout@v3
        with:
          path: "queue-nats"
          repository: awakari/queue-nats
          token: ${{ secrets.CLONE_PAT }}

      - name: clone reader
        uses: actions/checkout@v3
        with:
          path: "reader"
          repository: awakari/reader
          token: ${{ secrets.CLONE_PAT }}

      - name: clone resolver
        uses: actions/checkout@v3
        with:
          path: "resolver"
          repository: awakari/resolver
          token: ${{ secrets.CLONE_PAT }}

      - name: clone subscriptions-proxy
        uses: actions/checkout@v3
        with:
          path: "subscriptions-proxy"
          repository: awakari/subscriptions-proxy
          token: ${{ secrets.CLONE_PAT }}

      - name: clone semaphore-nats
        uses: actions/checkout@v3
        with:
          path: "semaphore-nats"
          repository: awakari/semaphore-nats
          token: ${{ secrets.CLONE_PAT }}

      - name: clone writer
        uses: actions/checkout@v3
        with:
          path: "writer"
          repository: awakari/writer
          token: ${{ secrets.CLONE_PAT }}

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.12.0

      - name: Helm dependency update
        continue-on-error: true
        run: |
          cd core
          helm dependency update helm/core

      - name: Helm package
        run: |
          cd core
          mkdir helm/package
          helm package helm/core --destination helm/package
          cd helm/package
          helm repo index .

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: core/helm/package
