name: Testing

on:
  push:
    branches:
      - "*"
      - "!master"

jobs:

  helm:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.12.0

      - name: Lint Helm Chart
        run: |
          helm dependency update helm/core
          helm lint helm/core
