name: Testing

on:
  push:
    branches:
      - "*"
      - "!master"

jobs:

  helm:
    runs-on: ubuntu-latest
    steps:

      - name: clone core
        uses: actions/checkout@v3
        with:
          path: "core"

      - name: clone conditions-text
        uses: actions/checkout@v3
        with:
          path: "conditions-text"
          repository: awakari/conditions-text

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.12.0

      - name: Lint Helm Chart
        run: |
          
          mkdir helm/core/charts
          cd helm/core/charts
          for i in conditions-text matches messages queue-nats reader subscriptions-proxy semaphore-nats writer; do helm package ../../../../$i/helm/$i; done
          cd ../../..
          
          helm dependency update helm/core
          helm lint helm/core
