name: Testing

on:
  push:
    branches:
      - "*"
      - "!master"

jobs:

  helm:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.12.0

      - name: Lint Helm Chart
        run: |
          cd ..
          for i in conditions-text matches messages queue-nats reader subscriptions-proxy semaphore-nats writer; do git clone git@github.com:awakari/$i.git; done
          cd core
          mkdir helm/core/charts
          cd helm/core/charts
          for i in conditions-text matches messages queue-nats reader subscriptions-proxy semaphore-nats writer; do helm package ../../../../$i/helm/$i; done
          cd ../../..
          helm dependency update helm/core
          helm lint helm/core
